FROM mcr.microsoft.com/playwright:v1.34.0-jammy

WORKDIR /playwright

COPY package*.json ./
COPY ./src src/
COPY ./e2e e2e/

RUN npm install -D @playwright/test

ENTRYPOINT ["npm", "run", "test:e2e"]

# docker build -t test_playwright:1.34.0 .
# docker run test_playwright:1.34.0
