FROM mcr.microsoft.com/playwright:v1.34.0-jammy

USER pwuser

WORKDIR /playwright

COPY --chown=pwuser:pwuser *.json ./
COPY --chown=pwuser:pwuser ./src src/
COPY --chown=pwuser:pwuser ./e2e e2e/

RUN mkdir "test-results"
RUN mkdir "playwright-report"
RUN npm install

ENTRYPOINT ["npx", "playwright", "test", "--config", "playwright.config.e2e.ts"]

# docker build -t test_playwright:1.34.0 .
# docker run test_playwright:1.34.0
