services:
  backend:
    build:
      context: ../backend/
      dockerfile: Dockerfile.backend
    ports:
      - "8000:9428"
    image: "backend:16.16.0"
    volumes:
      - database:/home/node/database
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9428/api/status || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ../front-end/
      dockerfile: Dockerfile.frontend
      args:
        - FRONTEND_DOMAIN=localhost
        - BACKEND_DOMAIN=localhost
        - BACKEND_PORT=8000
    ports:
      - "8080:4200"
    image: "frontend:16.16.0"
    environment:
      - DB_FOLDER="database"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:4200 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  database:
