services:
  backend:
    build:
      context: ../backend/
    ports:
      - "8000:9428"
    image: "backend:16.16.0"

  frontend:
    build:
      context: ../front-end/
      args:
        - FRONTEND_DOMAIN=localhost
        - BACKEND_DOMAIN=localhost
        - BACKEND_PORT=8000
    ports:
      - "8080:4200"
    image: "frontend:16.16.0"
    depends_on:
      - backend
