services:
  backend:
    build:
      context: ../backend/
      dockerfile: Dockerfile.backend
    ports:
      - "8000:9428"
    image: "backend:16.16.0"
    environment:
      - DB_FOLDER="database/e2e-starter"
    volumes:
      - database:/home/node/database
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://backend:9428/api/status || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ../front-end/
      dockerfile: Dockerfile.frontend
      args:
        - FRONTEND_DOMAIN=frontend
        - BACKEND_DOMAIN=backend
        - BACKEND_PORT=8000
    ports:
      - "8080:4200"
    image: "frontend:16.16.0"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://frontend:4200 || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 3

  playwright:
    build:
      context: ../front-end/
      dockerfile: Dockerfile.playwright
    image: "test_playwright:1.34.0"
    depends_on:
      frontend:
        condition: service_healthy
    volumes:
      - test_results:/playwright/test-results
      - test_reports:/playwright/playwright-report

volumes:
  database:
  test_results:
  test_reports:
