services:
  backend:
    build:
      context: ../backend/
    ports:
      - "8000:9428"
    image: "backend:16.16.0"
    volumes:
      - database:/home/node/database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ../front-end/
      args:
        - FRONTEND_DOMAIN=localhost
        - BACKEND_DOMAIN=localhost
        - BACKEND_PORT=8000
    ports:
      - "8080:4200"
    image: "frontend:16.16.0"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  database:
